name: Build LaTeX document
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build LaTeX document
      run: make

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f build/mn-sciagawka.pdf
        git commit -m "Add built PDF" -a || echo "No changes to commit"
        git push